apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - image: myrepo/myapp:0e7028c4248e1f198520d33875373ca16d78ed71
        imagePullPolicy: Always
        name: boardgame
        ports:
        - containerPort: 8080
